# Generated by Django 4.1.13 on 2026-01-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('running', 'Running'), ('walking', 'Walking'), ('strength', 'Strength Training'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('sports', 'Sports'), ('yoga', 'Yoga'), ('other', 'Other')], max_length=20)),
                ('duration_minutes', models.IntegerField()),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('calories_burned', models.IntegerField()),
                ('points_earned', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
